spring.application.name=sendemailspringboot
spring.mail.host=127.0.0.1
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

emails.sender_email=ahmed.12virageca@dd.com
emails.sender_name=ahmed
emails.sender_address=cite ghazela